apiVersion: v1
kind: Pod
metadata:
  name: app-server
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: sonarqube-server
spec:
  containers:
    - name: sonar
      image: sonarqube:alpine