apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-reader
  namespace: ns-dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: ns-dev
subjects:
  - kind: User
    name: course19
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: ns-dev
spec:
  containers:
    - name: web
      image: nginx:alpine