apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: Group
    name: developers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
data:
  domain: https://dev-api.company.com
  apiUrl: https://dev-api.company.com/api/v1