apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    app: frontend
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: sc-parameters
  namespace: ns-dev
stringData:
  dbHost: localhost
  dbPort: "3306"
  dbUser: user
  dbPass: "12345"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container
          image: nginx:alpine
          env:
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: dbHost
            - name: DBPORT
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: dbPort                  
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: dbUser
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: dbPass                                