apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: LimitRange
metadata:
  name: max-min-memory-cpu
  namespace: ns-dev
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100Mi
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: server-web
  namespace: ns-dev
spec:
  containers:
    - name: web
      image: nginx:alpine
      resources:
        limits:
          memory: 200Mi
          cpu: 1.5