apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: ns-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set
  namespace: ns-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
            requests:
              memory: 100Mi
              cpu: 50m
