apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: ns-dev
spec:
  hard:
    pods: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set
  namespace: ns-dev
spec:
  replicas: 8
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: serverweb
          image: nginx:alpine
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
            requests:
              memory: 100Mi
              cpu: 50m
