apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    app: frontend
    env: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: ns-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container
          image: nginx:alpine
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    app: frontend
    env: prd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: ns-prd
spec:
  replicas: 10
  selector:
    matchLabels:
      env: prd
      app: frontend
  template:
    metadata:
      labels:
        env: prd
        app: frontend
    spec:
      containers:
        - name: container
          image: nginx:alpine